import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {beforeEach,vi,test,expect} from 'vitest';
import App from './App';
import {api} from './api';
import type {AgentKind,AgentResult,KnowledgeBase} from './types';
vi.mock('./api',()=>({api:{summary:vi.fn(),agentStatus:vi.fn(),analyze:vi.fn(),upload:vi.fn(),query:vi.fn()}}));
const kb:KnowledgeBase={document_count:1,indexed_documents:1,chunk_count:2,supported_formats:['pdf','docx','csv','txt'],retrieval_ready:true,documents:[]};
const available={provider:'Local extractive analysis',mode:'extractive' as const,ready:true,message:'No generative LLM is running.',agents:['scope','risk','blockers']};
function outcome(kind:AgentKind):AgentResult{return {agent:kind,status:'partial',message:'Missing details remain unknown.',query:'review',provider:available.provider,generated_at:'2026-09-12T10:00:00Z',findings:[{category:'action_items',evidence_id:'a:chunk-1',quote:'Action item: arrange a review.',information_state:'unclear',owner:null,due_date:null,dates:[],source_status:null,severity:null,confidence:'explicit_source_statement'}],evidence:[{id:'a:chunk-1',document_id:'a',filename:'notes.txt',document_type:'txt',chunk_number:1,location:'Text section 2',text:'Action item: arrange a review.',similarity:0.4}],coverage:[{category:'action_items',state:'unclear',count:1},{category:'pending_decisions',state:'missing',count:0}],retrieved_count:2,evidence_limited:false,warnings:['Missing means not established in this evidence.']};}
async function clickRun(){const button=await screen.findByRole('button',{name:/Run analysis/});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);}
function show(path='/blockers'){render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);}
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.summary).mockResolvedValue(kb);vi.mocked(api.agentStatus).mockResolvedValue(available);});

test.each([['/scope','Scope & Deliverables'],['/risks','Risk & Delivery'],['/blockers','Blockers & Actions']])('agent route %s renders with honest provider status',async(path,title)=>{show(path);expect(await screen.findByRole('heading',{name:title})).toBeInTheDocument();expect(await screen.findByText('No generative LLM is running.')).toBeInTheDocument();expect(screen.getByRole('button',{name:/Run analysis/})).toBeEnabled();});
test('unknown owner and date are not invented, and source can be expanded',async()=>{vi.mocked(api.analyze).mockResolvedValue(outcome('blockers'));show();await clickRun();expect(await screen.findByText('Analysis complete · partial information')).toBeInTheDocument();expect(screen.getAllByText('Not stated')).toHaveLength(3);const reference=screen.getByText(/notes.txt · Text section 2/);const details=reference.closest('details')!;expect(details.open).toBe(false);fireEvent.click(reference);await waitFor(()=>expect(details.open).toBe(true));expect(screen.getByText('a:chunk-1')).toBeVisible();});
test('insufficient information state preserves missing categories',async()=>{vi.mocked(api.analyze).mockResolvedValue({...outcome('blockers'),status:'insufficient_information',findings:[],evidence:[],coverage:[{category:'action_items',state:'missing',count:0}]});show();await clickRun();expect(await screen.findByRole('heading',{name:'Insufficient information'})).toBeInTheDocument();expect(screen.getByText(/Not established in the retrieved evidence/)).toBeInTheDocument();});
test('analysis error can be retried',async()=>{vi.mocked(api.analyze).mockRejectedValueOnce(new Error('The analysis could not be verified.')).mockResolvedValueOnce(outcome('blockers'));show();await clickRun();expect(await screen.findByRole('alert')).toHaveTextContent('could not be verified');await clickRun();expect(await screen.findByText('Analysis complete · partial information')).toBeInTheDocument();});
test('loading state disables duplicate runs',async()=>{let finish:(value:AgentResult)=>void=()=>{};vi.mocked(api.analyze).mockReturnValue(new Promise(resolve=>{finish=resolve;}));show();await clickRun();expect(await screen.findByRole('status')).toHaveTextContent('Retrieving relevant passages');expect(screen.getByRole('button',{name:/Run analysis/})).toBeDisabled();finish(outcome('blockers'));await waitFor(()=>expect(screen.getByRole('button',{name:/Run analysis/})).toBeEnabled());});
test('empty knowledge base does not allow analysis',async()=>{vi.mocked(api.summary).mockResolvedValue({...kb,retrieval_ready:false,indexed_documents:0,document_count:0,chunk_count:0});show('/scope');expect(await screen.findByText('Add project evidence first')).toBeInTheDocument();expect(screen.getByRole('button',{name:/Run analysis/})).toBeDisabled();});
test('unavailable provider exposes a clear state',async()=>{vi.mocked(api.agentStatus).mockResolvedValue({...available,mode:'unavailable',ready:false,message:'Set LLM_MODEL.'});show('/scope');expect(await screen.findByRole('alert')).toHaveTextContent('Set LLM_MODEL.');expect(screen.getByRole('button',{name:/Run analysis/})).toBeDisabled();});
test('changing agents clears previous findings',async()=>{vi.mocked(api.analyze).mockResolvedValue(outcome('blockers'));show();await clickRun();await screen.findByText('Analysis complete · partial information');fireEvent.click(screen.getByRole('link',{name:'Scope & Deliverables'}));expect(await screen.findByRole('heading',{name:'Scope & Deliverables'})).toBeInTheDocument();expect(screen.queryByText('Analysis complete · partial information')).not.toBeInTheDocument();});
test('edited focus is sent to the selected agent',async()=>{vi.mocked(api.analyze).mockResolvedValue(outcome('risk'));show('/risks');fireEvent.change(await screen.findByLabelText('Analysis focus'),{target:{value:'Review API delivery risks'}});await clickRun();await waitFor(()=>expect(api.analyze).toHaveBeenCalledWith('risk','Review API delivery risks'));});
