import {render,screen,fireEvent,waitFor,within} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {vi,beforeEach,test,expect} from 'vitest';
import App from './App';
import {api} from './api';
import type {KnowledgeBase,ProjectDocument} from './types';
vi.mock('./api',()=>({api:{summary:vi.fn(),upload:vi.fn(),query:vi.fn(),agentStatus:vi.fn()}}));
const empty:KnowledgeBase={document_count:0,indexed_documents:0,chunk_count:0,supported_formats:['pdf','docx','csv','txt'],retrieval_ready:false,documents:[]};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(api.summary).mockResolvedValue(empty);vi.mocked(api.agentStatus).mockResolvedValue({provider:'Local extractive analysis',mode:'extractive',ready:true,message:'Source extraction available.',agents:['scope','risk','blockers']});});
function show(path='/dashboard'){render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);}
test('overview empty state and navigation',async()=>{show();expect(await screen.findByText('Your project, in focus.')).toBeInTheDocument();fireEvent.click(screen.getByRole('link',{name:'Documents'}));expect(await screen.findByText('Add your project documents')).toBeInTheDocument();});
test('backend failure is visible and retry works',async()=>{vi.mocked(api.summary).mockRejectedValueOnce(new Error('Backend unavailable'));show();expect(await screen.findByRole('alert')).toHaveTextContent('Backend unavailable');fireEvent.click(screen.getByText('Retry connection'));expect(await screen.findByText('Your project, in focus.')).toBeInTheDocument();});
test('query returns insufficient information',async()=>{vi.mocked(api.summary).mockResolvedValue({...empty,retrieval_ready:true,indexed_documents:1,document_count:1,chunk_count:1});vi.mocked(api.query).mockResolvedValue({status:'insufficient_information',message:'No relevant evidence found.',query:'cake',results:[]});show('/retrieval');fireEvent.change(await screen.findByLabelText('What would you like to find?'),{target:{value:'cake'}});fireEvent.click(screen.getByRole('button',{name:/Find evidence/}));expect(await screen.findByRole('heading',{name:'Insufficient information'})).toBeInTheDocument();expect(api.query).toHaveBeenCalledWith('cake');});
test('retrieval displays actual source passage and provenance',async()=>{vi.mocked(api.summary).mockResolvedValue({...empty,retrieval_ready:true,indexed_documents:1,document_count:1,chunk_count:1});vi.mocked(api.query).mockResolvedValue({status:'ok',message:'Relevant source passages.',query:'API owner',results:[{id:'abc:chunk-1',document_id:'abc',filename:'notes.txt',document_type:'txt',chunk_number:1,location:'Text section 1',text:'Priya owns the API.',similarity:0.65}]});show('/retrieval');fireEvent.change(await screen.findByLabelText('What would you like to find?'),{target:{value:'API owner'}});fireEvent.click(screen.getByRole('button',{name:/Find evidence/}));expect(await screen.findByText('Priya owns the API.')).toBeInTheDocument();expect(screen.getByText('notes.txt')).toBeInTheDocument();expect(screen.getByText('abc:chunk-1')).toBeInTheDocument();});
test('multi-file upload keeps failed file visible',async()=>{const doc:ProjectDocument={id:'a',filename:'bad.pdf',document_type:'pdf',size_bytes:3,uploaded_at:'2026-09-10',status:'error',chunk_count:0,indexed:false,error:'No readable text found.'};vi.mocked(api.upload).mockImplementation(async()=>{vi.mocked(api.summary).mockResolvedValue({...empty,document_count:1,documents:[doc]});return {documents:[doc]};});show('/documents');const input=await screen.findByLabelText('Choose project documents');fireEvent.change(input,{target:{files:[new File(['bad'],'bad.pdf')]}});fireEvent.click(screen.getByRole('button',{name:/Upload & index/}));expect(await within(await screen.findByRole('table')).findByText('No readable text found.')).toBeInTheDocument();expect(within(screen.getByRole('table')).getByText('Failed',{selector:'span'})).toBeInTheDocument();});
test('upload error allows retry',async()=>{vi.mocked(api.upload).mockRejectedValue(new Error('Upload unavailable'));show('/documents');fireEvent.change(await screen.findByLabelText('Choose project documents'),{target:{files:[new File(['text'],'notes.txt')]}});fireEvent.click(screen.getByRole('button',{name:/Upload & index/}));expect(await screen.findByRole('alert')).toHaveTextContent('Upload unavailable');await waitFor(()=>expect(screen.getByRole('button',{name:/Upload & index/})).toBeEnabled());});
test('indexed-only knowledge base and statistics',async()=>{vi.mocked(api.summary).mockResolvedValue({...empty,document_count:2,indexed_documents:1,chunk_count:3,retrieval_ready:true,documents:[{id:'b',filename:'source.txt',document_type:'txt',size_bytes:100,uploaded_at:'2026-09-10',status:'indexed',chunk_count:3,indexed:true,error:null}]});show('/knowledge-base');expect(await screen.findByText('source.txt')).toBeInTheDocument();expect(screen.getByText('Retrieval available')).toBeInTheDocument();});
